canonical: https://gematik.de/fhir/ISiK
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul 1.0.0 CC1
name: Implementierungsleitfaden ISiK-Basismodul 1.0.0 CC1
status: active
version: "1.0"
dependencies:
  de.basisprofil.r4: 1.1.0
