canonical: https://gematik.de/fhir/ISiK/v2
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul Stufe2 1.0.0 CC1
name: Implementierungsleitfaden ISiK-Basismodul Stufe2 1.0.0 CC1
status: draft
version: "1.0.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.3.0-alpha1
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1